### PR TITLE
Add ingress api version compatibility

### PR DESCRIPTION
**Pull request by DoGab**
Add ingress api version compatibility for extensions/v1beta1, networking.k8s.io/v1beta1, networking.k8s.io/v1

Bump Chart version

Signed-off-by: Dominic Gabriel <domi94@gmx.ch>

#### What this PR does / why we need it:

With new Kubernetes versions, new ingress api versions have been added and the backend service fields have changed. So far this Chart is not compatible with the latest Kubernetes version if you want to use ingress created by the chart. This PR fixes this issue and makes the ingress compatible with Kubernetes 1.20 but also keeps it backwards compatible with previous ingress api versions.

Mention the maintainers:
- @fzalila 
- @alexnuttinck 

Tested with the following values on Kubernetes Version 1.20 and 1.18:
```
service:
    type: ClusterIP

  ingress:
    enabled: true
    hosts:
      - host: adminer.local
 ```

#### Which issue this PR fixes

I didn't open an issue for the chart but fixed it myself and contributed this PR.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by imilic1** [comment]
can someone please merge this pull request?

**Comment by lapwat** [comment]
Hello please merge this, and update the chart version to 0.1.8 because 0.1.7 is already taken.

**Comment by DoGab** [comment]
Updated the version to 0.1.8 but still can't merge the PR because the owners are inactive... @fzalila and @alexnuttinck can you please accept?

**Comment by lapwat** [comment]
@derjohn @banzo

**Review by banzo — APPROVED** [review]

**Pull request merged**
