### PR TITLE
Mv/ingress version

### PR DESCRIPTION
**Pull request by devopsmariocom**
Signed-off-by: Mario Vejlupek <mario@vejlupek.cz>

#### What this PR does / why we need it:

1. migrating Ingress object to networking.k8s.io/v1 as extensions/v1beta1 and networking.k8s.io/v1beta1 are being removed https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122 
2. adding className support

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by lapwat** [comment]
Please merge this fix

**Comment by banzo** [comment]
@elmariofredo Thank you for the contribution, I think #6 takes care of this issue, so I close the PR. Let me know if I am missing something.

**Comment by elmariofredo** [comment]
@banzo sure #6 is good. I wanted to keep backward compatibility, but I don't think that this is relevant at this moment 😉

**Comment by banzo** [comment]
Reopening for #11

**Comment by banzo** [comment]
@elmariofredo do you recall why you changed from `pathType: Prefix` to `pathType: ImplementationSpecific`?

https://github.com/cetic/helm-adminer/pull/13/conflicts

**Comment by elmariofredo** [comment]
@banzo, @toabi I have followed migration notes see https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

> pathType is now required for each specified path. Options are Prefix, Exact, and ImplementationSpecific. To match the undefined v1beta1 behavior, use ImplementationSpecific.

Reality is that ImplementationSpecific == Prefix in 99% clusters, but if you want I can change it to Prefix ;)

**Pull request merged**
